### ISSUE TITLE
[BE] 재무제표 DB에 넣기 

### ISSUE THREAD

**Issue by sangeun815** [Ama-Get-Don/Ama-Get-Don#16]
- [ ] 최근 연간 실적 재무 정보
- [ ] 최근 분기 실적 재무 정보 
- [ ] 각 주요 재무 정보

**Comment by S-SIRIUS** [comment]
**어떻게 사용자가 입력한 텍스트에서 특정 회사라는 것을 알고 DB에 쿼리를 날릴 것인가?** 의 문제가 있습니다.
