### ISSUE TITLE
로그인 api 개발

### ISSUE THREAD

**Issue by sangeun815** [Ama-Get-Don/Ama-Get-Don#31]

**Comment by S-SIRIUS** [comment]
{
  "user_create": {
    "tookie_id": "string",
    "name": "string",
    "password1": "string",
    "password2": "string",
    "email": "user@example.com",
    "phone_number": "string",
    "birth": "string",
    "gender": "string",
    "investment_level": 0
  },
  "investmentPreference_create": {
    "user_id": 0,
    "investment_goal": "string",
    "risk_tolerance": "string",
    "investment_ratio": "string",
    "investment_period": "string",
    "income_status": "string",
    "derivatives_experience": "string"
  }
}
